define({
	wrap : "wrap_main",
	date : {
		"wrap"                         : "calendar_wrap",
		"set_wrap"                     : "calendar_set_wrap",
		"set_button"                   : "calendar_set_button",
		"set_date"                     : "calendar_set_date",
		"calendar"                     : "calendar_calendar",
		"calendar_part"                : "calendar_calendar_part",
		"date_month_wrap"              : "calendar_date_month_wrap",
		"date_month_text"              : "calendar_date_month_text",
		"date_month_wrap"              : "calendar_date_month_wrap",
		"date_current_month_text"      : "calendar_date_current_month_text",
		"calendar_day_name"            : "calendar_calendar_day_name",
		"calendar_day_number_selected" : "calendar_calendar_day_number_selected",
		"calendar_day_number"          : "calendar_calendar_day_number",
		"calendar_year_text"           : "calendar_calendar_year_text",
		"calendar_year_text_selected"  : "calendar_calendar_year_text_selected",
		"calendar_day_seperator"       : "calendar_calendar_day_seperator",
		"calendar_month_text"          : "calendar_calendar_month_text",
		"calendar_month_text_selected" : "calendar_calendar_month_text_selected"
	},
	tree : { 
		"wrap"                           : "tree_wrap",
		"tree_wrap"                      : "tree_tree_wrap",
		"branch"                         : "tree_branch",
		"branch_children"                : "tree_branch_children",
		"branch_text"                    : "tree_branch_text",
		"branch_text_wrap"               : "tree_branch_text_wrap",
		"branch_text_wrap_active"        : "tree_branch_text_wrap_active",
		"branch_text_badge"              : "tree_branch_text_badge",
		"branch_text_option_wrap_active" : "tree_branch_text_option_wrap_active",
		"branch_text_option_wrap"        : "tree_branch_text_option_wrap",
		"branch_text_option_active"      : "tree_branch_text_option_active",
		"branch_text_option"             : "tree_branch_text_option",
		"branch_text_option_button_wrap" : "tree_branch_text_option_button_wrap",
		"branch_text_option_button"      : "tree_branch_text_option_button",
		"result_wrap"                    : "tree_result_wrap",
		"result_path_wrap"               : "tree_result_path_wrap",
		"result_choice"                  : "tree_result_choice",
		"result_text"                    : "tree_result_text",
		"result_path"                    : "tree_result_path",
		"result_button_wrap"             : "tree_result_button_wrap",
		"result_button"                  : "tree_result_button",
	},
	radio : {
		"wrap"          : "radio_wrap",
		"item"          : "radio_item",
		"item_selected" : "radio_item_selected",
		"input"         : { 
			"wrap"         : "wrap_input",
			"text_valid"   : "input_text_valid",
			"text_invalid" : "input_text_invalid",
			"small"        : "input_small",
			"large"        : "input_large"
		}
	},
	select : { 
		"main"                 : "dropdown_main",
		"option_selected_wrap" : "option_selected_wrap",
		"option_selected"      : "option_selected",
		"option_selector"      : "option_selector",
		"option_wrap"          : "option_wrap",
		"option"               : "option",
	},
	text : {
		"wrap"      : "wrap_text",
		"regular"   : "regular_text",
		"imporant"  : "imporant_text",
		"underline" : "imporant_text",
		"italic"    : "italic_text",
		"title"     : "title"
	},
	list : { 
		"wrap"           : "wrap_list",
		"item_wrap"      : "wrap_list_item",
		"item_notation"  : "list_item_notation",
		"item_text_wrap" : "list_item_text_wrap",
		"item_text"      : "list_item_text",
		"item_list"      : "list_item_list",
	},
	input : {
		"wrap"               : "wrap_input",
		"text_valid"         : "input_text_valid",
		"text_invalid"       : "input_text_invalid",
		"small"              : "input_small",
		"large"              : "input_large",
		"suggest_container"  : "input_suggest_container",
		"suggest"            : "input_suggest",
		"suggest_text"       : "input_suggest_text",
		"suggest_text_match" : "input_suggest_text_match",
	}
})